Creating a service class, mapper, repository and changing the control…
piotr-grosicki/project-jdp-2305-01 pull request #16
Opened 2023-05-11 21:54 UTC by Sawikr

…ler class using ResponseEntity with GlobalHttpErrorHandler support

2023-05-12 08:31 UTC, Sawikr commented
Uwaga do encji Group. Grupa jest zastrzeżonym słowem kluczowym, nie można jej używać jako nazwy tabeli. Dlatego użycie go jako nazwy tabeli prowadzi do błędu. Aby uniknąć takiego błędu, trzeba użyć symbolu załączonego znaku wstecznego wokół nazwy tabeli „grupa”. Przykład @Entity(name = "`GROUPS`").  Znak to `, poniżej tyldy po lewej stronie. Link: https://www.tutorialspoint.com/mysql-syntax-error-in-select-query-while-using-group-as-table-name

2023-05-12 09:51 UTC, PawelKowalskiSD requested changes
brakuje mi testów

2023-05-12 09:51 UTC, PawelKowalskiSD commented on src/main/java/com/kodilla/ecommercee/exception/TaskNotFoundException.java
> +}
TaskNotFoundException ?

2023-05-12 11:23 UTC, Sawikr commented
> brakuje mi testów

Fakt, dorobię. Zrobiłem testy w Postmanie i dołączyłem w komentarzu.

2023-05-12 11:24 UTC, Sawikr commented on src/main/java/com/kodilla/ecommercee/exception/TaskNotFoundException.java
> +}
> TaskNotFoundException ?

To globalny wyjątek, może dotyczyć wszystkich encji. Nie upieram się można zmienić podejście. Można zmienić na ProductNotFoundException i dołożyć wyjątek dla Product w GlobalHttpErrorHandler.
Proszę o propozycję, co proponujesz?

2023-05-17 17:11 UTC, Feemssu approved these changes

2023-05-17 19:47 UTC, PawelKowalskiSD approved these changes

2023-05-17 20:58 UTC, Sawikr commented on src/main/java/com/kodilla/ecommercee/exception/GlobalHttpErrorHandler.java
> +}
Tak

2023-05-17 21:28 UTC, PawelKowalskiSD approved these changes

2023-05-17 21:29 UTC, merged