ProductController implemented endpoints
piotr-grosicki/project-jdp-2305-01 pull request #2
Opened 2023-05-02 04:22 UTC by Feemssu

2023-05-02 06:46 UTC, piotr-grosicki requested changes
pracujemy na dto, nie na generic entity. Encje nigdy nie powinny byc uzywane w controllerach

2023-05-02 06:49 UTC, Feemssu commented
miałem tak zrobione tylko inaczej zinterpretowałem to co napisali na czacie grupowym, poprawię dzisiaj :)

2023-05-02 17:43 UTC, piotr-grosicki requested changes
konflikty (google: how to resolve merge conflicts in intellij)

2023-05-02 20:00 UTC, Feemssu commented
mam nadzieje, że teraz jest ok

2023-05-03 06:53 UTC, piotr-grosicki requested changes

2023-05-03 06:53 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @GetMapping(value = "{id}")
nie zgrywa sie z nazwa parametru metody

2023-05-03 06:53 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public void deleteProduct(Long productId){}
brakuje path variable

2023-05-03 06:53 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public ProductDto getProduct(Long productId){
brakuje path variable

2023-05-03 19:50 UTC, piotr-grosicki requested changes

2023-05-03 19:50 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @DeleteMapping
brakuje value z path variable

2023-05-04 07:43 UTC, merged