added empty endpoints for a user controller
piotr-grosicki/project-jdp-2305-01 pull request #6
Opened 2023-05-02 13:50 UTC by SzmitPawel

2023-05-02 14:12 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2023-05-02 15:47 UTC, SzmitPawel commented
dodałem guild.gradle może to jest przyczyną że brakowało dodanych zależności

2023-05-02 16:05 UTC, SzmitPawel commented
> projekt sie nie buduje

dodałem guild.gradle może to jest przyczyną że brakowało dodanych zależności

2023-05-02 17:43 UTC, piotr-grosicki requested changes
konflikty (google: how to resolve merge conflicts in intellij)

2023-05-02 18:57 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2023-05-02 18:58 UTC, SzmitPawel commented
> konflikty (google: how to resolve merge conflicts in intellij)

no i oczywiście coś zwaliłem :(
Nie wiem dlaczego zrobiło mi merge z main

2023-05-02 19:00 UTC, piotr-grosicki commented
> > konflikty (google: how to resolve merge conflicts in intellij)
> 
> 
> 
> no i oczywiście coś zwaliłem :(
> 
> Nie wiem dlaczego zrobiło mi merge z main.
> 
> Wiem że można to cofnąć, ale nie mam uprawnien


no ale wlasnie to miales zrobic, konflikty likwiduje sie przez merge z main. Tylko tak rozwiazales te konflikty ze branch teraz sie nie buduje :)

2023-05-02 19:18 UTC, SzmitPawel commented
tylko że zmiany dotyczyły build.gradle, po rozwiązaniu konfliktu i wykonaniu
merge z main błędy zaczęły dotyczyć GroupController a to było z innej branch (JDP230501-2),konflikt
tego nie dotyczył

2023-05-03 06:55 UTC, piotr-grosicki commented
> tylko że zmiany dotyczyły build.gradle, po rozwiązaniu konfliktu i wykonaniu
> 
> merge z main błędy zaczęły dotyczyć GroupController a to było z innej branch (JDP230501-2),konflikt
> 
> tego nie dotyczył.
> 
> 
> 
> Czy mam naprawić ten błąd ? 
> 
> 

no musisz, group controller dziala na main, przestal dzialac na twojej branchy co oznacza, ze na twojej branchy znajduje sie blad

2023-05-03 18:59 UTC, SzmitPawel commented
poprawione

2023-05-03 19:51 UTC, merged